name: hlg
favicon: null
layout_spectrum: 0.41676681814715266
typography_spectrum: 0.5337458613794297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0957342276815325
  lightness: 0.489683679305017
  saturation: 0.7629437309224159
  rhythmicContrast: 0.32915897108614445
purpose: []
